### ISSUE TITLE
Link broken

### ISSUE THREAD

**Issue by pstew** [tgerke/github-actions-with-r#1]
https://github.com/Moffitt-Health-Informatics/moffittdocs returns a 404. Can you please provide the updated link?

**Comment by tgerke** [comment]
That repo is not fully public; I tried to find where I reference `moffittdocs` in this repo, but couldn't. Is there a particular place where I need to repair or redirect?

**Comment by pstew** [comment]
I see! Actually I am not sure. Rodrigo was looking for something on the Bio-Data Club repository and commented that this link was broken. I will ask him.

**Comment by tgerke** [comment]
Emailed you both a working internal link 😀
